services:
  - type: web
    name: facebook-messenger-bot
    env: node
    plan: free
    buildCommand: node build.cjs
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production